# Generated by Django 5.2.9 on 2026-01-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cultural", "Cultural"),
                            ("sports", "Sports"),
                            ("technical", "Technical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_group_event", models.BooleanField(default=False)),
                ("min_team_size", models.IntegerField(default=1)),
                ("max_team_size", models.IntegerField(default=1)),
                ("event_date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="Registration.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("roll_no", "event")},
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=100)),
                ("member_roll_no", models.CharField(blank=True, max_length=20)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="Registration.eventregistration",
                    ),
                ),
            ],
        ),
    ]
